### ISSUE TITLE
The original EdiFabric is not closed

### ISSUE THREAD

**Issue by DonZoeggerle** [Silvenga/EdiWeave#4]
The original repository is not closed and is located [here](https://github.com/EdiFabric/Archived)

https://github.com/EdiFabric/Archived

**Comment by Silvenga** [comment]
Which is why you are posting this message to other forks?

> I'm the owner of what was the real ediFabric repository on GitHub. This has now been taken down and ediFabric is now a registered trade mark, and only available through our website or partners. Could you please remove the edifabric fork and do not publish any of edifabric's proprietary source code (although it's very old and with significant issues) to GitHub or else ?
https://github.com/eleooo/ediFabric/pull/1

Closing as not constructive.

**Comment by DonZoeggerle** [comment]
Is the original repository on GitHub right now - Yes.
Has the repository always been on GitHub, albeit under different owners - Yes
Are you using the original repository in full - Yes
Are you claiming that the original repository is closed - Yes

Deceit is not constructive. You could have used the energy to create something of your own.
I'll be republishing this every now and then - we won't be bullied by anybody.
