### ISSUE TITLE
Where is the link to the original repository ?

### ISSUE THREAD

**Issue by DonZoeggerle2** [Silvenga/EdiWeave#7]
The README falsely implies that the original repository is taken down or have been taken down. 

The original repository has always been available on GitHub since its inception (Feb 2015). 

Until this falsehood is corrected I, or one of the other contributors, will raise this as an issue and will provide an attribution to the original. After all, we created ~99.99% of the source code here and at least we deserve some honesty.

[Link to the Original EdiFabric](https://github.com/EdiFabric/Archived)

**Comment by Silvenga** [comment]
> The README falsely implies that the original repository is taken down or have been taken down.

Did you not say? Was that a lie?
> I'm the owner of what was the real ediFabric repository on GitHub. This has now **been taken down** and ediFabric is now a registered trade mark, and only available through our website or partners.

![image](https://user-images.githubusercontent.com/2753330/37676237-5984308c-2c45-11e8-8127-bdfd305a7509.png)

You chose to make use of the open source community when it benefited you, but then chose to disrespect and disregard the community as a whole when you removed the code (you removed the repository) and other community contributions (you removed issues, etc.).
